"""UI-independent OpenWhisper application core."""

from .audio import (
    AudioCapture,
    AudioCaptureConfig,
    AudioDevice,
    AudioDeviceError,
    AudioLevelEvent,
    BufferedParecAudioCapture,
    CapturedAudio,
    ParecAudioCapture,
    QtMultimediaAudioCapture,
    TempAudioManager,
)
from .compute import ComputeBackend, ComputeCapability, ComputeProbe, ComputeProbeResult
from .config import AppConfig, AppPaths, ConfigStore, migrate_legacy_config
from .desktop import (
    AtspiAccessibilityBackend,
    CapabilityDesktopIntegration,
    DesktopCapabilities,
    DesktopIntegration,
    InsertionTarget,
    PortalGlobalShortcutBackend,
    QtDbusGlobalShortcutsPortalTransport,
    X11ShortcutBackend,
    detect_desktop_capabilities,
)
from .history import HistoryRecord, HistoryStatistics, SQLiteHistoryStore
from .insertion import (
    DesktopSession,
    DesktopTextInserter,
    InsertionMethod,
    InsertionResult,
    OutputMode,
    WaylandTextBackend,
    X11TextBackend,
    contains_rtl,
)
from .models import (
    CleanupProvider,
    Transcript,
    TranscriptionProvider,
    TranscriptSegment,
    deduplicate_segments,
)
from .personalization import (
    BUILTIN_MODES,
    BUILTIN_TRANSFORMS,
    ActivationRule,
    CleanupStyle,
    CommandOutcome,
    CommandValidator,
    ConfigurationProposal,
    ContextPolicy,
    ContextSource,
    DictationContext,
    HistoryQuery,
    KeyAction,
    ModeDefinition,
    ModeRouter,
    Snippet,
    SQLitePersonalizationStore,
    TextOutput,
    TransformDefinition,
    TransformEngine,
    TransformKind,
    TransformPreview,
    VocabularyEntry,
    apply_snippets,
    apply_vocabulary,
    smart_format,
)
from .readiness import ReadinessCheck, ReadinessChecker, ReadinessReport, ReadinessStatus
from .retention import AudioRetentionPolicy, RetainedAudio, RetainedAudioManager
from .session import (
    CleanupMode,
    DictationSession,
    SessionBusyError,
    SessionOutcome,
    SessionState,
)
from .shortcuts import ShortcutController, ShortcutMode

__all__ = [
    "AppConfig",
    "AppPaths",
    "AudioCapture",
    "AudioRetentionPolicy",
    "ActivationRule",
    "BUILTIN_MODES",
    "BUILTIN_TRANSFORMS",
    "AudioCaptureConfig",
    "AudioDevice",
    "AudioDeviceError",
    "AudioLevelEvent",
    "AtspiAccessibilityBackend",
    "BufferedParecAudioCapture",
    "CapturedAudio",
    "CleanupMode",
    "CleanupProvider",
    "CleanupStyle",
    "CapabilityDesktopIntegration",
    "CommandOutcome",
    "CommandValidator",
    "ConfigurationProposal",
    "ConfigStore",
    "ComputeBackend",
    "ComputeCapability",
    "ComputeProbe",
    "ComputeProbeResult",
    "ContextPolicy",
    "ContextSource",
    "DesktopSession",
    "DesktopCapabilities",
    "DesktopIntegration",
    "DesktopTextInserter",
    "DictationSession",
    "DictationContext",
    "HistoryRecord",
    "HistoryQuery",
    "HistoryStatistics",
    "InsertionMethod",
    "InsertionResult",
    "OutputMode",
    "InsertionTarget",
    "KeyAction",
    "ModeDefinition",
    "ModeRouter",
    "ParecAudioCapture",
    "RetainedAudio",
    "RetainedAudioManager",
    "ReadinessCheck",
    "ReadinessChecker",
    "ReadinessReport",
    "ReadinessStatus",
    "QtMultimediaAudioCapture",
    "QtDbusGlobalShortcutsPortalTransport",
    "SQLiteHistoryStore",
    "SQLitePersonalizationStore",
    "SessionBusyError",
    "SessionOutcome",
    "SessionState",
    "ShortcutController",
    "ShortcutMode",
    "Snippet",
    "TextOutput",
    "TempAudioManager",
    "Transcript",
    "TranscriptSegment",
    "TranscriptionProvider",
    "WaylandTextBackend",
    "TransformDefinition",
    "TransformEngine",
    "TransformKind",
    "TransformPreview",
    "VocabularyEntry",
    "X11TextBackend",
    "X11ShortcutBackend",
    "PortalGlobalShortcutBackend",
    "contains_rtl",
    "detect_desktop_capabilities",
    "apply_snippets",
    "apply_vocabulary",
    "deduplicate_segments",
    "migrate_legacy_config",
    "smart_format",
]
